version: "3.8"
services:

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: "dynamodb-local"
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  aws-cli-local:
    depends_on:
      - "dynamodb-local"
    command:
      - aws dynamodb create-table \
        --table-name maido_table \
        --billing-mode=PAY_PER_REQUEST \
        --attribute-definition AttributeName=PK,AttributeType=S AttributeName=SK,AttributeType=S \
        --key-schema AttributeName=PK,KeyType=HASH AttributeName=SK,KeyType=RANGE \
        --endpoint-url http://localhost:8000
    image: amazon/aws-cli
    container_name: aws-cli-local
    environment:
      AWS_ACCESS_KEY_ID: "example"
      AWS_REGION: "example"
      AWS_SECRET_ACCESS_KEY: "example"
